### ISSUE TITLE
Should DuckPAN prompt to upgrade or install DDG when new version detected?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#107]
Currently if a new version of the DDG package has been released, or a new version of DuckPAN has been released, DuckPAN becomes unusable as it prevents you from carrying out any other actions until the appropriate package has been updated.

I was thinking we should either prompt the dev in that moment to run the upgrade for them, which leads to a slightly nicer and a hopefully quicker experience. Or alternatively, DuckPAN could simply run the script to update DuckPAN itself rather than making the dev take any action.

Any thoughts?

//cc @jagtalon @russellholt @jdorweiler @mwmiller

**Comment by mintsoft** [comment]
Closing: duckpan does this now and has for ages I think?
