### ISSUE TITLE
DuckPAN errors when t/ directory exists beside root of repo, e.g. zeroclickinfo-goodies/

### ISSUE THREAD

**Issue by djinn** [duckduckgo/p5-app-duckpan#11]
I suspect that I have missed some step or set some environment variable incorrectly. I was successfully able to install duckpan. When I try to run duckpan server, I receive two kinds of errors.

*  Several plugins use **share** function which duckpan or I am able to figure out how to fullfil ( I deleted those plugins for now)
* All plugins when tested issue error not being able to find "module_share_dir" which I suspect is html template and javascript directory.  

With this I have hit a dead end. Would like to know what I might be doing wrong?

**Comment by zachthompson** [comment]
Should be addressed by https://github.com/duckduckgo/duckduckgo/pull/117
