### ISSUE TITLE
RAR archives?

### ISSUE THREAD

**Issue by gim-** [duckduckgo/p5-app-duckpan#137]
Today I decided to investigate what I can do with DuckDuckHack and there is something I really don't understand. I had an impression of DuckDuckGo being closer to free and open source world than many other alternatives, but now I see how README suggests to download DuckDuckHack Development Virtual Machine (https://github.com/duckduckgo/p5-app-duckpan#duckduckhack-development-virtual-machine) which is packed into such an ugly proprietary format as RAR which requires downloading non-free software to extract it. That's a bit disappointing. Why not to use just ZIP or 7Z for this?

**Comment by moollaza** [comment]
Fixed in #182
