### ISSUE TITLE
Correct version not being pulled from duckpan.org?

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/p5-app-duckpan#195]
DDGC was recently bumped to 1.000:

```
$ duckpan DDGC
You have a newer (0.983) version of DDGC than duckpan (0)
```

`$duckpan_module_version` not being set correctly? `version->parse` should be OK with this format.

**Comment by moollaza** [comment]
@jbarrett are you able to replicate this? It seems to be working correctly for me

**Comment by moollaza** [comment]
Ah, I managed to get it to appear. Making the install script a little more informative.

**Comment by moollaza** [comment]
And the reason is that DuckPAN actually doesn't have a version # for DDGC right now!

![2015-01-28_22h05_23](https://cloud.githubusercontent.com/assets/873785/5951776/cb2f2e38-a739-11e4-8ff5-6b0aabccb4d0.png)

A re-release of DDGC should hopefully fix this!
