### ISSUE TITLE
Duckpan Wrong Layout/Style

### ISSUE THREAD

**Issue by puskin94** [duckduckgo/p5-app-duckpan#199]
Hi, sometimes Web duckpan ( at 0.0.0.0:5000 ) breaks page's layout, like CSS is not loaded.
![schermata 2015-01-07 alle 15 52 36](https://cloud.githubusercontent.com/assets/8344987/5647357/710edf94-9685-11e4-92ac-064f6c7dd705.jpg)
Is it happening only to me?? I don't know the cause ;(

**Comment by mintsoft** [comment]
@puskin94 Can you check the developer tools for any 404's or javascript errors etc?

**Comment by puskin94** [comment]
@mintsoft  just checked , no luck :(

**Comment by mintsoft** [comment]
@puskin94 is there anyreason you're using 0.0.0.0? That's the "everything on this machine" address when used for binding; have you tried 127.0.0.1 instead?

**Comment by puskin94** [comment]
@mintsoft No reason, but http://0:5000/ === http://0.0.0.0:5000/
No errors, nothing but
```

    <!--

     DDG Homepage 

    -->
    <html>
        <head></head>
        <body></body>
    </html>
```

**Comment by mintsoft** [comment]
@puskin94 yeah exactly; `0.0.0.0` has a special meaning; it's the all addresses bind address, the default route address etc

**Comment by puskin94** [comment]
@mintsoft Ok, you are right, but no solution using 127.0.0.1 ;(

**Comment by mintsoft** [comment]
Hmm, does it fix itself with a hard-refresh? Are there error logs on the console where `duckpan server` is running?

**Comment by puskin94** [comment]
No interesting logs on duckpan, after a computer reset nothing changes.... Wait, now the page is totally blank

**Comment by mintsoft** [comment]
Hmm, totally blank would be consistent with the markup snippet you presented earlier. Have you tried clearing your browser's cache?

**Comment by puskin94** [comment]
@mintsoft Yep, no changes since this morning. Now the situation is like
![schermata 2015-01-08 alle 09 31 13](https://cloud.githubusercontent.com/assets/8344987/5659855/8272bcc6-9719-11e4-9637-ca32833ca5e5.jpg)

**Comment by puskin94** [comment]
@mintsoft Ok, I have an Idea.
```
Checking asset cache...
[DDG Homepage] page_root.html recently cached -- no request made.
[DDG SERP] page_spice.html recently cached -- no request made.
[DDG SERP] parsing for additional assets
[via DDG SERP] [Main JS] dpan1720.js recently cached -- no request made.
[via DDG SERP] [Templating JS] g1220.js recently cached -- no request made.
[via DDG SERP] [t922.css CSS] t922.css recently cached -- no request made.
[via DDG SERP] [s922.css CSS] s922.css recently cached -- no request made.
[via DDG SERP] [Locales JS] locales.20150107.113720.js recently cached -- no request made.
[DDG SERP] assets loaded
Starting up webserver...
```

This is about that some page is already in cache, so if some are not loaded correctly,  I will see it again and again. Where Is this DDG cache?? Deleting browser's Cache changes nothing!

**Comment by mintsoft** [comment]
@jagtalon @moollaza I'm not familiar with the internals of duckpan; can you assist?

**Comment by puskin94** [comment]
@mintsoft @jagtalon @moollaza I think that this bug can be avoided adding a file checksum control... any feedback?

**Comment by moollaza** [comment]
@puskin94 hey there -- pleas try running `duckpan -e -v server` and let me know how it goes.

The duckpan cache is located in `~/.duckpan/cache`

**Comment by moollaza** [comment]
Note the `-e` is an alias for `--empty` which forces the cache to be cleared. There is logic in place to make sure the file downloads completely, but I will take another peek to see if there's any holes.

If you're interested in investigating it yourself, everything happens here:
https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/Cmd/Server.pm#L365

**Comment by puskin94** [comment]
@moollaza Thanks but before this solution, I fixed using duckpan Reinstall; however, I realized how duckpan broke: my terminal crashed in the moment when cache was loading builing the web server, so the cache is corrupt. I don't know how often this happen, but I think that can be upgraded adding a checksum control!

**Comment by mintsoft** [comment]
Thanks for the info @moollaza I'll recommend that in future with any other cache-esque problems

**Comment by moollaza** [comment]
@puskin94 I'm glad to hear you managed to fix it. Running `reinstall` first clears the cache so that's likely how the problem was resolved.

The checksum idea is interesting but given that the issue hasn't come up before (that I'm aware of) it might be overkill for now. If it happens for others we can certainly investigate a way to make sure it doesn't happen again!

**Comment by puskin94** [comment]
@moollaza glad to hear that I had an interesting idea!! I think that this problem will occur again all the times duckpan will crash while it is loading!
