### ISSUE TITLE
README.md Vagrant setup instructions have changed

### ISSUE THREAD

**Issue by mikedep333** [duckduckgo/p5-app-duckpan#201]
The setup instructions for the vagrant virtual environment have changed.
https://github.com/shedd/duckpan-vagrant/blob/master/README.md

The changes were necessary due to changes in Ubuntu 14.04 hosts, Vagrant itself, and in vagrant-berkshelf.
https://github.com/shedd/duckpan-vagrant/commit/799ba2800dc3ada5aa8f1b5c5594e2173aa27f8f
https://github.com/shedd/duckpan-vagrant/commit/6b67391203f29d2e82f387b67114db71015ef0cc

However, the setup instructions are now longer. Note that the section "Workaround for Linux distros not supported by the ChefDK" is effectively part of the instructions.

IMHO, there are 3 possible ways to handle this:
1. Update p5-app-duckpan/README.md to include all the necessary details from duckpan-vagrant/README.md , but not every single detail.
2. Update p5-app-duckpan/README.md to tell users to follow the instructions under duckpan-vagrant/README.md .
3. Move duckpan-vagrant under the DuckDuckGo organization on GitHub (IIRC, @malbin wanted to do this.) Then update p5-app-duckpan/README.md to tell users to follow the instructions under duckpan-vagrant/README.md

**Comment by moollaza** [comment]
@mikedep333 thanks for this. 

Who owns DuckPAN-Vagrant? I don't mind moving it under DDG but I'm not sure if we've committed to maintaining it. I would assume if we own it, we'd be expected to maintain it.

I like option 2 for an immediate fix if right now the doc's are incorrect.

**Comment by mikedep333** [comment]
Hi @moollaza 

[Robert Shedd](https://github.com/shedd) owns it.

We should ask @malbin about this. I am spending some of my free time maintaining it. I recently fixed a few issues.
https://github.com/shedd/duckpan-vagrant/issues/27
https://github.com/shedd/duckpan-vagrant/issues/28

I prefer Option 2 also.

**Comment by malbin** [comment]
@moollaza brings up a good point. I probably don't have the resources to take it on personally and so agree that Option 2 makes more sense.

**Comment by mikedep333** [comment]
OK, I will implement option 2 and send a PR.
