### ISSUE TITLE
page_root.html - header logo should point to local duckpan server

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/p5-app-duckpan#221]
Not sure this is possible, only a suggestion as it may involve injecting html changes into page_root.html. 

It would be nice if the header logo `href` pointed to the users local testing server address instead of duckduckgo.com 

![selection_198](https://cloud.githubusercontent.com/assets/5282264/6124805/8a42fa50-b14b-11e4-893f-a0ea4a866955.png)

``` html
<a tabindex="-1" href="http://duckduckgo.com/" class="header__logo-wrap"><span class="header__logo">DuckDuckGo</span></a>
```

//CC @moollaza

**Comment by moollaza** [comment]
@MrChrisW good idea! This is definitely possible. We already modify a bunch of the links when we pull down the HTML from DuckDuckGo.com so this shouldn't be too difficult
