### ISSUE TITLE
More/Better debug output (perhaps a --debug flag?)

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#222]
A new dev was trying to create a Spice IA that didn't need to return an answer to an API. He was unable to determine why his IA didn't appear in the output from `duckpan query` when he tested the triggers.

It turns out he had `return;` instead of `return "";` which obviously meant his IA was bailing out, so nothing was returned to the console.

I was thinking we should be able to indicate whenever an IA truly triggers, i.e. the `handle` is executed` but returns `undef` (meaning it bailed out)

This output might get really noisy though, so perhaps a special `--debug` flag is necessary?

@jagtalon @killerfish @MrChrisW @mintsoft any thoughts?

**Comment by MrChrisW** [comment]
:+1: Yes please! I keep forgetting you can use `DDG_BLOCK_TRACE=1` flag to get more information :laughing: . A debug argument would make life easier.

**Comment by mintsoft** [comment]
Absolutely; I always forget about `DDG_BLOCK_TRACE`; `--verbose=` or `--debug` is definitely more nix standard

**Comment by killerfish** [comment]
i think we already have a --verbose, just add this under that flag perhaps?
