### ISSUE TITLE
Exclude reload on frontend code changes

### ISSUE THREAD

**Issue by mattr555** [duckduckgo/p5-app-duckpan#224]
DuckPAN now reloads when you update the code (#196) :+1: :+1: 

However, the seconds I have to wait for the server to unnecessarily reload when I make a CSS change on a spice might add up to whole minutes if I develop for DDH for the rest of my life :stuck_out_tongue_closed_eyes:

Could we skip the reload if the changed files are CSS/JS/Handlebars on a spice? (I know it's different for  goodies, so it may not work universally)

**Comment by moollaza** [comment]
@mattr555 sorry about that! We actually have a fix that's already merged in, I've just forgotten to release DuckPAN. Will do that now and it should all be fixed!
