### ISSUE TITLE
VMWare image "duckpan upgrade" fails

### ISSUE THREAD

**Issue by tommytommytommy** [duckduckgo/p5-app-duckpan#225]
Running "duckpan upgrade" on the VMWare image from https://duck.co/duckduckhack/installing_duckpan gave me the following error message, and I was unable to force it to install the missing dependency using the options available for <code>duckpan upgrade</code> (probably because I just don't know how to?)

<pre>You already have latest version of DDG with 0.131

--> Working on http://duckpan.org/authors/id/M/MO/MOOLLAZA/App-DuckPAN-0.175.tar.gz
Fetching http://duckpan.org/authors/id/M/MO/MOOLLAZA/App-DuckPAN-0.175.tar.gz ... OK
Configuring App-DuckPAN-0.175 ... OK
==> Found dependencies: autodie
--> Working on autodie
Fetching http://www.cpan.org/authors/id/N/NT/NTHYKIER/autodie-2.26.tar.gz ... OK
Configuring autodie-2.26 ... OK
Building and testing autodie-2.26 ... FAIL
! Installing autodie failed. See /home/dax/.cpanm/work/1423741362.12939/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Installed version (2.20) of autodie is not in range '2.25'
! Bailing out the installation for App-DuckPAN-0.175.
</pre>

**Comment by tommytommytommy** [comment]
Here's the build log:

<pre>
cpanm (App::cpanminus) 1.6937 on perl 5.016003 built for x86_64-linux
Work directory is /home/dax/.cpanm/work/1423741362.12939
You have make /usr/bin/make
You have LWP 6.09
You have /bin/tar: tar (GNU tar) 1.26
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
--> Working on http://duckpan.org/authors/id/M/MO/MOOLLAZA/App-DuckPAN-0.175.tar.gz
Fetching http://duckpan.org/authors/id/M/MO/MOOLLAZA/App-DuckPAN-0.175.tar.gz
-> OK
Unpacking App-DuckPAN-0.175.tar.gz
Entering App-DuckPAN-0.175
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.72)
Checking if you have File::ShareDir::Install 0.06 ... Yes (0.10)
Configuring App-DuckPAN-0.175
Running Makefile.PL
Warning: prerequisite autodie 2.25 not found. We have 2.20.
Checking if your kit is complete...
Looks good
Writing Makefile for App::DuckPAN
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have WWW::DuckDuckGo 0.015 ... Yes (0.015)
Checking if you have Pod::Usage 1.63 ... Yes (1.64)
Checking if you have HTML::TreeBuilder 5.03 ... Yes (5.03)
Checking if you have Text::Xslate v3.0.0 ... Yes (3.3.3)
Checking if you have Starman 0.4008 ... Yes (0.4011)
Checking if you have autodie 2.25 ... No (2.20 < 2.25)
Checking if you have Crypt::SSLeay 0.58 ... Yes (0.64)
Checking if you have MooX 0.101 ... Yes (0.101)
Checking if you have Dist::Zilla::Plugin::UploadToDuckPAN 0.006 ... Yes (0.007)
Checking if you have List::MoreUtils 0.33 ... Yes (0.33)
Checking if you have Term::ReadKey 2.32 ... Yes (2.32)
Checking if you have MooX::Options 3.71 ... Yes (3.83)
Checking if you have Try::Tiny 0.22 ... Yes (0.22)
Checking if you have Term::ANSIColor 4.03 ... Yes (4.03)
Checking if you have Dir::Self 0.10 ... Yes (0.10)
Checking if you have File::HomeDir 1.00 ... Yes (1.00)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.72)
Checking if you have File::ShareDir::ProjectDistDir 0.003002 ... Yes (0.4.4)
Checking if you have Test::More 0.98 ... Yes (1.001014)
Checking if you have File::Temp 0.22 ... Yes (0.22)
Checking if you have HTML::Parser 3.71 ... Yes (3.71)
Checking if you have POE 1.354 ... Yes (1.354)
Checking if you have Email::Valid 0.187 ... Yes (0.190)
Checking if you have Term::ProgressBar 2.16 ... Yes (2.17)
Checking if you have Config::INI 0.019 ... Yes (0.020)
Checking if you have File::Which 1.09 ... Yes (1.09)
Checking if you have File::chdir 0.1008 ... Yes (0.1008)
Checking if you have Test::Script::Run 0.05 ... Yes (0.05)
Checking if you have Module::Data 0.006 ... Yes (0.006)
Checking if you have Perl::Version 1.013 ... Yes (1.013)
Checking if you have LWP::Protocol::https 6.06 ... Yes (6.06)
Checking if you have Data::Printer 0.3 ... Yes (0.35)
Checking if you have CPAN::Repository 0.007 ... Yes (0.008)
Checking if you have LWP::Simple 6.00 ... Yes (6.09)
Checking if you have Parse::CPAN::Packages::Fast 0.08 ... Yes (0.08)
Checking if you have Path::Tiny 0.058 ... Yes (0.061)
Checking if you have File::Find::Rule 0.33 ... Yes (0.33)
Checking if you have Module::Pluggable 4.8 ... Yes (5.1)
Checking if you have URI 1.60 ... Yes (1.60)
Checking if you have Plack 1.0029 ... Yes (1.0034)
Checking if you have Term::UI 0.30 ... Yes (0.30)
Checking if you have Moo 1.002000 ... Yes (1.003000)
Checking if you have Class::Load 0.18 ... Yes (0.20)
Checking if you have version 0.96 ... Yes (0.99)
Checking if you have File::FindLib 0.001001 ... Yes (0.001001)
Checking if you have App::cpanminus 1.7014 ... Yes (1.7025)
Checking if you have MooX::Cmd 0.001 ... Yes (0.003)
Checking if you have Filesys::Notify::Simple 0.12 ... Yes (0.12)
Checking if you have Dist::Zilla 4.300007 ... Yes (4.300035)
Checking if you have Test::LoadAllModules 0.021 ... Yes (0.022)
Checking if you have JSON 2.9 ... Yes (2.90)
==> Found dependencies: autodie
Searching autodie on cpanmetadb ...
--> Working on autodie
Fetching http://www.cpan.org/authors/id/N/NT/NTHYKIER/autodie-2.26.tar.gz
-> OK
Unpacking autodie-2.26.tar.gz
Entering autodie-2.26
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.72)
Configuring autodie-2.26
Running Makefile.PL
Checking if your kit is complete...
Looks good
Writing Makefile for autodie
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Scalar::Util 0 ... Yes (1.25)
Checking if you have FindBin 0 ... Yes (1.51)
Checking if you have File::Spec 0 ... Yes (3.40)
Checking if you have IO::Handle 0 ... Yes (1.33)
Checking if you have Fcntl 0 ... Yes (1.11)
Checking if you have if 0 ... Yes (0.0602)
Checking if you have POSIX 0 ... Yes (1.30)
Checking if you have lib 0 ... Yes (0.63)
Checking if you have Socket 0 ... Yes (2.001)
Checking if you have File::Copy 0 ... Yes (2.23)
Checking if you have warnings 0 ... Yes (1.13)
Checking if you have parent 0 ... Yes (0.225)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (6.72)
Checking if you have overload 0 ... Yes (1.18)
Checking if you have constant 0 ... Yes (1.23)
Checking if you have B 0 ... Yes (1.35)
Checking if you have Exporter 5.57 ... Yes (5.66)
Checking if you have Carp 0 ... Yes (1.26)
Checking if you have open 0 ... Yes (1.10)
Checking if you have Test::More 0 ... Yes (1.001014)
Checking if you have strict 0 ... Yes (1.07)
Checking if you have Import::Into 0 ... Yes (1.001001)
Checking if you have File::Temp 0 ... Yes (0.22)
Checking if you have Tie::RefHash 0 ... Yes (1.39)
Building and testing autodie-2.26
cp lib/autodie/hints.pm blib/lib/autodie/hints.pm
cp lib/autodie/ScopeUtil.pm blib/lib/autodie/ScopeUtil.pm
cp lib/Fatal.pm blib/lib/Fatal.pm
cp lib/autodie/Scope/Guard.pm blib/lib/autodie/Scope/Guard.pm
cp lib/autodie/exception.pm blib/lib/autodie/exception.pm
cp lib/autodie/Scope/GuardStack.pm blib/lib/autodie/Scope/GuardStack.pm
cp lib/autodie/skip.pm blib/lib/autodie/skip.pm
cp lib/autodie.pm blib/lib/autodie.pm
cp lib/autodie/exception/system.pm blib/lib/autodie/exception/system.pm
Manifying blib/man3/autodie::hints.3
Manifying blib/man3/autodie::ScopeUtil.3
Manifying blib/man3/Fatal.3
Manifying blib/man3/autodie::Scope::Guard.3
Manifying blib/man3/autodie::exception.3
Manifying blib/man3/autodie::Scope::GuardStack.3
Manifying blib/man3/autodie::skip.3
Manifying blib/man3/autodie::exception::system.3
Manifying blib/man3/autodie.3
PERL_DL_NONLAZY=1 /home/dax/perl5/perlbrew/perls/perl-5.16.3/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-load.t ...................... ok
t/args.t ......................... ok
t/author-critic.t ................ skipped: these tests are for testing by the author
t/autodie.t ...................... ok
t/backcompat.t ................... ok
t/basic_exceptions.t ............. ok
t/binmode.t ...................... ok
t/blog_hints.t ................... ok
t/caller.t ....................... ok
t/chmod.t ........................ ok
t/chown.t ........................ ok
t/context.t ...................... ok
t/context_lexical.t .............. ok
t/core-trampoline-slurp.t ........ ok
t/crickey.t ...................... ok
t/critic.t ....................... skipped: Author test.  Set $ENV{AUTHOR_TESTING} to true to run.
t/dbmopen.t ...................... ok
t/eval_error.t ................... ok
t/exception_class.t .............. ok
t/exceptions.t ................... ok
t/exec.t ......................... ok
t/Fatal.t ........................ ok
t/filehandles.t .................. ok
t/fileno.t ....................... ok
t/flock.t ........................ ok
t/fork.t ......................... skipped: BSD::Resource required to test fork()
t/format-clobber.t ............... ok
# Sub::Identify is not loaded
t/hints.t ........................ ok
t/hints_insist.t ................. ok
t/hints_pod_examples.t ........... ok
t/hints_provider_does.t .......... ok
t/hints_provider_easy_does_it.t .. ok
t/hints_provider_isa.t ........... ok
Unquoted string "autodie" may clash with future reserved word at /home/dax/.cpanm/work/1423741362.12939/autodie-2.26/t/lib/my/pragma.pm line 7.
Couldn't build importer for 1: syntax error at (eval 5) line 2, at EOF
BEGIN failed--compilation aborted at t/import-into.t line 16.
t/import-into.t .................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
t/internal-backcompat.t .......... ok
t/internal.t ..................... ok
t/kill.t ......................... ok
t/kwalitee.t ..................... skipped: Author test.  Set $ENV{RELEASE_TESTING} to true to run.
t/lethal.t ....................... ok
t/lex58.t ........................ ok
t/mkdir.t ........................ ok
t/no_carp.t ...................... ok
t/open.t ......................... ok
t/pod-coverage.t ................. skipped: Author test.  Set $ENV{AUTHOR_TESTING} to true to run.
t/pod.t .......................... skipped: Author test.  Set $ENV{AUTHOR_TESTING} to true to run.
t/read.t ......................... ok
t/recv.t ......................... ok
t/release-pod-coverage.t ......... skipped: these tests are for release candidate testing
t/release-pod-syntax.t ........... skipped: these tests are for release candidate testing
t/repeat.t ....................... ok
t/rt-74246.t ..................... ok
t/scope_leak.t ................... ok
t/skip.t ......................... ok
t/socket.t ....................... skipped: Author test.  Set $ENV{AUTHOR_TESTING} to true to run.
t/string-eval-basic.t ............ ok
t/string-eval-leak.t ............. ok
t/sysopen.t ...................... ok
t/system.t ....................... ok
t/truncate.t ..................... ok
t/unlink.t ....................... ok
t/user-context.t ................. ok
t/usersub.t ...................... ok
t/utf8_open.t .................... ok
t/utime.t ........................ ok
t/version.t ...................... skipped: Release test.  Set $ENV{RELEASE_TESTING} to true to run.
t/version_tag.t .................. ok

Test Summary Report
-------------------
t/import-into.t                (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=66, Tests=499,  3 wallclock secs ( 0.18 usr  0.06 sys +  2.19 cusr  0.30 csys =  2.73 CPU)
Result: FAIL
Failed 1/66 test programs. 0/499 subtests failed.
make: *** [test_dynamic] Error 255
-> FAIL Installing autodie failed. See /home/dax/.cpanm/work/1423741362.12939/build.log for details. Retry with --force to force install it.
-> FAIL Installing the dependencies failed: Installed version (2.20) of autodie is not in range '2.25'
-> FAIL Bailing out the installation for App-DuckPAN-0.175.
</pre>

**Comment by moollaza** [comment]
@tommytommytommy thanks for reporting this! Seems like the newest version of autodie is having some trouble installing on some machines (it installed fine on Travis). What OS was this being installed on?

**Comment by tommytommytommy** [comment]
I didn't make any other modifications to the VMWare image; here's the output from <pre>cat /etc/lsb-release</pre>
<pre>
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=12.04
DISTRIB_CODENAME=precise
DISTRIB_DESCRIPTION="Ubuntu 12.04.2 LTS"
</pre>

**Comment by mikedep333** [comment]
Hi @tommytommytommy 

I am maintaining the DuckDuckHack VM.

Are you running the original DuckDuckHack VM? (`ddh-vmw.rar`) Or are you running the 2 newer versions: `ddh-vmw-2014-12-13.ova` or `ddh-vmw-2014-12-23.ova`?

You can tell the original version version apart from the 2 newer versions because it has no "Update Ubuntu" shortcut on the desktop.

I just tried out the `ddh-vmw-2014-12-23` version, and there was no update for autodie.
[duckpan-update.log](http://pastebin.com/Xd9pzXmB)
[`duckpan upgrade` output](http://pastebin.com/7hPdwJyH)

Even if you are running the old VM and do not wish to switch to the new VM, I will still try to help you upgrade DuckPAN successfully.

**Comment by tommytommytommy** [comment]
Hi @mikedep333,

I installed what I believe is the original VM linked at https://duck.co/duckduckhack/installing_duckpan
There is no "Update Ubuntu" shortcut on my desktop.

Forcing the install of autodie using <code>cpanm autodie --force</code> fixed my problem. Out of curiosity, where are the newer VM images available at?

Thanks!

**Comment by moollaza** [comment]
Whoops! I forgot to update the DDG docs with the new DuckPAN readme. Right now we're duplicating the README in the Docs so you got the link to the old VM.

I'll fix that right now!

**Comment by moollaza** [comment]
Updated Docs here: https://github.com/duckduckgo/duckduckgo-documentation/pull/202

**Comment by moollaza** [comment]
@tommytommytommy would you mind trying out the new VM and seeing how it goes?

**Comment by tommytommytommy** [comment]
@moollaza I downlaoded the new VMWare image and gave it a try. I'm not sure if this change was intentional, but I only received a terminal prompt when starting up the machine. The old version presented a GUI along with Firefox and Sublime. Duckpan itself seems to work fine (I was able to upgrade successfully as well as run <code>duckpan query</code> after cloning the Spice repository).

**Comment by moollaza** [comment]
>Duckpan itself seems to work fine (I was able to upgrade successfully as well as run duckpan query after cloning the Spice repository). 

@tommytommytommy glad to hear it works!

> I only received a terminal prompt when starting up the machine. The old version presented a GUI along with Firefox and Sublime.

I didn't realize this changed either! @mikedep333 do you know anything about that? Any idea why we changed it? Is there a way to get a GUI?

**Comment by mikedep333** [comment]
@tommytommytommy @moollaza That's not an intentional change! That's a bug! X is failing to start for some reason. It is probably related to VMware Tools.

Here is what you should be seeing immediately after boot:
http://imgur.com/10lzaAN,sJun8h5#1
And after you press enter:
http://imgur.com/10lzaAN,sJun8h5#0

What VMware product are you using (Workstation, Player, ESXi) and what exact version are you using?

Before I launched, I tested the VM with VMware Workstation 11.0.0, which corresponds to VMware Player 7. I also tested it with VMware Player 4.0.6, which corresponds to VMware Workstation 8.0.6, weeks before I launched.

It has the Ubuntu Packages open-vm-tools, open-vm-dkms & open-vm-toolbox installed at version `2011.12.20-562307-0ubuntu1`. They should support a wide range of VMware products.

**Comment by tommytommytommy** [comment]
@mikedep333 I'm using VMWare Fusion Professional 7.1.0 (2314774) on OS X Yosemite (10.10.2), on a iMac with 8 gigs of memory, a 2.7 GHz Intel Core i5 processor, and an NVIDIA GeForce GT 640M 512 MB graphics card. When I initially tried to import <code>ddh-vbox-2014-12-23.ova</code>, I received the following error message:

![screen shot 2015-02-14 at 12 33 38 pm 2](https://cloud.githubusercontent.com/assets/5326740/6200439/2ef732ee-b446-11e4-9403-0bbff29b890c.png)

After clicking okay, it sent me to the terminal where I was able to successfully clone the spice repository and upgrade duckpan.

**Comment by mikedep333** [comment]
@tommytommytommy The problem is that you imported the VirtualBox VM rather than the VMWare VM. You need to import the latter. [ddh-vmw-2014-12-23.ova](https://ddg-community.s3.amazonaws.com/ddh-vmw-2014-12-23.ova)

**Comment by tommytommytommy** [comment]
@mikedep333 Ah, all fixed. Sorry for wasting your time! Thanks for the help.

**Comment by mikedep333** [comment]
@tommytommytommy No Problem. Glad to help.
