### ISSUE TITLE
Validation of duck.co credentials during duckpan setup fails

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/p5-app-duckpan#226]
```
$ duckpan setup
We require some general information about you

What is your username on https://duck.co/ ? jbarrett

What is your password on https://duck.co/ ? (password)
Checking your account on https://duck.co/... 
Account lookup failed!
```

**Comment by jbarrett** [comment]
[It POSTs `username` and `password` variables to https://duck.co/my/login](https://github.com/duckduckgo/p5-app-duckpan/blob/b12671b/lib/App/DuckPAN.pm#L516-L523)

https://duck.co/my/login has changed to have a random username field name as a form of CSRF/naive automation protection.

We can change the login form to do something different, or we can scrape this field name before POSTing the credentials.

**Comment by jbarrett** [comment]
Thinking we could probably nix this on the login form? What does CSRF protection really earn us prior to log in? @moollaza

**Comment by jbarrett** [comment]
Tangentially related, @bsstoner had the following output when his config was missing:

```
[01:51 PM ubuntu@brian ~ ]$ duckpan poupload homepage.po
Uploading homepage.po... 
[FATAL]  No configuration found for your https://duck.co/ username and password
[FATAL]  Please use 'dzil setup' first!
```

Is that our text? Shouldn't it say `duckpan setup`? `dzil setup` will just do PAUSE creds, right?

**Comment by moollaza** [comment]
@jbarrett yup that's our text. I think in this case it should say "duckpan setup" but that's just a proxy for 'dzil setup' because the config file actually exists in `.dzil/config`

**Comment by jbarrett** [comment]
`duckpan setup` also has its own code to do duck.co credentials.

**Comment by moollaza** [comment]
@jbarrett sorry, you're right -- duckpan just checks if there's any info in an existing dzil config file, but it should be copying/storing everything in it's own config. 

I'll fix this

**Comment by jbarrett** [comment]
I think they're OK in dzil's config, but we should maybe check for the keys rather than presence of the file.
