### ISSUE TITLE
check_ddg/check_duckpan: should also look for pinned version

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#236]
Right now the `check_ddg` (and `check_duckpan`) functions don't consider pinned versions.

If a pinned version exists that is higher than the installed version, an upgrade should be enforced. If however a pinned version exists that is equal or below the installed version, the check should pass.

Borrowing code from Perl.pm should make this fix simple.

**Comment by zachthompson** [comment]
Pretty sure this works.
