### ISSUE TITLE
Warn when expected JS/CSS file isn't found

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#247]
It's easy to make a typo in the sharedir/filename for a given Spice (and now Goodie). DuckPAN should warn when it detects paths which don't match an existing package and should similarly warn when JS/CSS files exist that are incorrectly named.

It would probably help if DuckPAN explained what it's looking for/expecting when the files aren't found.

/cc @zachthompson thoughts?

**Comment by moollaza** [comment]
There was a related issue I made a while ago, #14

**Comment by zachthompson** [comment]
I was actually looking at the original issue a few days ago.  Probably a fine idea. Is there a chance that there would be legitimate js not named how we think they should be?  I'd like to avoid unnecessary warnings. Then people start tuning out altogether.

**Comment by moollaza** [comment]
> Is there a chance that there would be legitimate js not named how we think they should be?

Nope. We only look for and load the JS file that correlates to the package. Anything else, for now, shouldn't exist.
