### ISSUE TITLE
DDG 0.136 Build Fails Tests

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/p5-app-duckpan#258]
Not related to DuckPAN. Related to DDG core https://github.com/duckduckgo/duckduckgo

Attempting to run an upgrade from DDG version 0.134 to [0.136](https://github.com/duckduckgo/duckduckgo/releases/tag/0.136) fails due to the `DDG::(Goodie|Spice|Fathead|Longtail)Bundle::OpenSourceDuckDuckGo` dependencies.  

Attempted manual build: See full [build.log](https://gist.github.com/MrChrisW/794e24904126c0c5199b#file-build-log-L169)

Relevant part: `Can't locate DDG/LongtailBundle/OpenSourceDuckDuckGo.pm in @INC (you may need to install the DDG::LongtailBundle::OpenSourceDuckDuckGo module)`

Marking as **high** priority as all `duckpan` instances will request updating to version 0.136 on execution. 

@moollaza

**Comment by mattr555** [comment]
Can replicate.

**Comment by javathunderman** [comment]
Yep, getting this too.

**Comment by moollaza** [comment]
Working on a fix...

for now you can run:
`duckpan DDG::GoodieBundle::OpenSourceDuckDuckGo DDG::SpiceBundle::OpenSourceDuckDuckGo DDG::FatheadBundle::OpenSourceDuckDuckGo DDG::LongtailBundle::OpenSourceDuckDuckGo`

**Comment by moollaza** [comment]
Alright guys, this *should* be fixed now. 

I've released a new version of DuckPAN. It should auto install the missing modules for you. It also no longer forces you to upgrade DuckPAN or DDG, but will constantly remind you that there's a new version.

**Comment by MrChrisW** [comment]
@moollaza Thanks!

**Comment by moollaza** [comment]
Actually hold on, I don't think it's entirely fixed yet...
