### ISSUE TITLE
DDH1 Endpoint Down

### ISSUE THREAD

**Issue by MrChrisW** [duckduckgo/p5-app-duckpan#263]
The http://ddh1.duckduckgo.com endpoint is down. This is causing issues as DuckPan will default to this endpoint if no API keys are found locally. 

https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/Web.pm#L162

Reported in the following comments:
https://github.com/duckduckgo/zeroclickinfo-spice/issues/1930#issuecomment-113702179
https://github.com/duckduckgo/zeroclickinfo-spice/issues/1562#issuecomment-113030344

//CC @zachthompson @moollaza

**Comment by MrChrisW** [comment]
@moollaza ping!

**Comment by zachthompson** [comment]
@MrChrisW This is a pita.  I'll take a look at it today.

**Comment by moollaza** [comment]
@MrChrisW sorry I hadn't seen this yet. I'll get DDH1 back online, I didn't realize the whole machine was offline!

**Comment by moollaza** [comment]
OK looks like the ops team has a task to get this machine back online. I believe Amazon had to do something with the hardware, hence it went offline.

**Comment by MrChrisW** [comment]
@moollaza No problem, thanks for the details its always appreciated! 

I'll close this now as #264 should resolve this issue once a release is made.
