### ISSUE TITLE
After dzil installing repo, `duckpan server` says repo not installed.

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#267]
When running `duckpan server` we check to make sure modules are up to date.

After installing the Goodei repo with dzil I ran `duckpan server` and it seems to think the Goodie bundle is not installed.

Oddly, it also returns a blank number for the "local package version" (which we should be detecting and handling properly)

![1____projects_zeroclickinfo-goodies__ssh_](https://cloud.githubusercontent.com/assets/873785/9446508/21a067d6-4a60-11e5-9647-6a8ae0755ce4.png)

/cc @zachthompson

**Comment by zachthompson** [comment]
I can't reproduce with `dzil install` and `duckpan server`.

1. Can you verify the version actually installed in /usr/local manually?
2. What is `ds` actually running?  If it's just `duckpan server`, what does `which duckpan` return?

**Comment by moollaza** [comment]
@zachthompson sorry about the aliases!

- `ds` is simply `duckpan server`, `di` is `dzil install`.
- `which duckpan` reports `/usr/local/ddg.cpan/perl5/bin/duckpan`
- `duckpan help` shows that the version is **0.189**

**Comment by zachthompson** [comment]
Can you reproduce by running those commands again?  If so maybe I need to jump on your instance because I still can't.
