### ISSUE TITLE
`duckpan latest` uses latest DuckPAN version number for DDG package?

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#273]
@zachthompson after testing and installing your DuckPAN PR my installed version had been bumped up and I wanted to reset things, so I decided to run `duckpan latest`.

For some reason though I'm running into some really odd behaviour:

When executing `duckpan latest` it notices my version of DuckPAN is different from the latest release (it seems to think it's not installed based on the message, but that's another issue...).

However, it immediately fails, claiming that it couldn't find version 0.190 (the latest version of DuckPAN) of the **DDG** package on duckpan.org.

Somehow it's trying to find the wrong version of DDG and this is causing things to fail.

I spent some time reading the code and `warn`ing stuff and couldn't come to any conclusions about how `$version` is getting the value `0.190` for the latest version of DDG.

Here's what I'm seeing:
```
$ duckpan latest
Emptying DuckPAN cache...
DuckPAN cache emptied
[NOTICE] You don't have App::DuckPAN installed. Installing version (0.190)
[FATAL]  Failed to find version 0.190 of DDG
```

Can you replicate this at all?

**Comment by moollaza** [comment]
Also happening on my dev machine:

![1____projects_zeroclickinfo-goodies__ssh_](https://cloud.githubusercontent.com/assets/873785/10271906/32d00204-6ae6-11e5-9267-96a53480e0b9.png)

**Comment by moollaza** [comment]
Oddly, `duckpan reinstall` works correctly, using your new code as well:

![1____projects_zeroclickinfo-goodies__ssh_](https://cloud.githubusercontent.com/assets/873785/10271922/7978b066-6ae6-11e5-80e3-56ba159e1dca.png)

But after this, `duckpan latest` still produces the same error.

**Comment by zachthompson** [comment]
@moollaza https://github.com/duckduckgo/p5-app-duckpan/pull/274
