### ISSUE TITLE
Switch to using Beta.ddg as primary (or only?) machine for API Key fallback

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#282]
When a dev uses Duckpan and triggers a Spice that requires an API key, duckpan first checks the local ENV. If the key is not found, it directs the API call to DDH10 and falls back to DDH 9...1 if the requests are not successful.

Currently all our DDH machines are being used by ongoing projects and some of these machines don't seem to be handling the API calls as expected. Right now DDH 10 is being used internally and I can't update + redeploy it. The API call still returns a 200, but the response contains no JSON so DuckPAN thinks it was OK, causing the IA not to work at all.

I think we need to rely on a machine that we can expect to be up to date and that can be easily updated + deployed if we're having problems. To me it sounds like Beta.duckduckgo.com makes sense.

I think we should swap out depending on DDH 10-1 and instead just rely on Beta.

Thoughts?

---

> Related: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2183#issuecomment-157375671

/cc @zachthompson @jdorweiler @jagtalon

**Comment by jagtalon** [comment]
@moollaza I have this in https://github.com/duckduckgo/p5-app-duckpan/pull/271 and I think it's a good idea.
