### ISSUE TITLE
DuckPAN renders (i) icon incorrectly

### ISSUE THREAD

**Issue by mintsoft** [duckduckgo/p5-app-duckpan#292]
![image](https://cloud.githubusercontent.com/assets/978048/11908584/442403fa-a5d5-11e5-82a3-5aa10b5bb503.png)

I'm not sure why it's so poorly positioned?

**Comment by Jedidiah** [comment]
Adding `overflow: auto;` to `.zcm__sep--h` gets rid of the wee grey block, but I'm not sure why it's only an issue when running duckpin locally and not in production.

**Comment by moollaza** [comment]
@Jedidiah thanks for that, worst case, I'll see if we can add some custom CSS for DuckPAN, but I'd like to avoid that.

---

@bsstoner @jdorweiler do you know if we have any JS that modifies the dom to allow for the location of the `i` icon to be on the right side?

also, any ideas on why that grey block appears there? I suspect it has something to do with how we're modifying the answer bar...

**Comment by GuiltyDolphin** [comment]
@mintsoft I think I've figured out what's being changed, but I have no idea why!

![screenshot from 2016-01-23 16 13 54](https://cloud.githubusercontent.com/assets/8598426/12531221/e54e595a-c1ec-11e5-8fcc-0c0f0a930aed.png)

![screenshot from 2016-01-23 16 12 08](https://cloud.githubusercontent.com/assets/8598426/12531223/edf584ca-c1ec-11e5-8156-225ddd63557e.png)

For the icon:

![screenshot from 2016-01-23 16 21 51](https://cloud.githubusercontent.com/assets/8598426/12531251/732c6668-c1ed-11e5-8faa-1b306a480f61.png)

Working duckpan:

![screenshot from 2016-01-23 16 11 59](https://cloud.githubusercontent.com/assets/8598426/12531226/f538b874-c1ec-11e5-9f17-ce98d0272bdb.png)

Original duckpan:

![screenshot from 2016-01-23 16 19 43](https://cloud.githubusercontent.com/assets/8598426/12531238/34f810a4-c1ed-11e5-82d0-b67ed412d474.png)

Also, what's up with Dax?

DuckPAN:

![screenshot from 2016-01-23 16 23 07](https://cloud.githubusercontent.com/assets/8598426/12531256/9b998716-c1ed-11e5-952b-b6b13571486b.png)

Beta:

![screenshot from 2016-01-23 16 23 29](https://cloud.githubusercontent.com/assets/8598426/12531260/a777f0fe-c1ed-11e5-8cae-7f36e66b0291.png)

I've noticed a few other differences between DuckPAN and Beta - such as the `Send feedback` button.

**Comment by moollaza** [comment]
@mintsoft @Jedidiah most of this has been fixed with the recent CSS changes on the main site. The `i` still appears in the bottom left. I believe the fix is to solve #310 -- ensure the CSS order matches the main site.
