### ISSUE TITLE
Outdated link to documentation with "duckpan new"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/p5-app-duckpan#297]
![screen shot 2016-01-15 at 2 22 08 am](https://cloud.githubusercontent.com/assets/81969/12347763/e92fd0ae-bb2e-11e5-8f9e-6067b279e0cd.png)

Links to duck.co instead of docs.duckduckhack.com

**Comment by MrChrisW** [comment]
@jagtalon Fixed in 

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2050
https://github.com/duckduckgo/zeroclickinfo-spice/pull/2409

**Comment by jagtalon** [comment]
@MrChrisW oh, whoops! Thank you!
