### ISSUE TITLE
Name of the IA is not added in the test file after "duckpan new"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/p5-app-duckpan#300]
It says `/js/spice//query` instead of `/js/spice/grunt/query`

![screen shot 2016-01-15 at 3 29 32 am](https://cloud.githubusercontent.com/assets/81969/12348779/4cfb4eb6-bb38-11e5-8886-8ff339d5cb58.png)

**Comment by MrChrisW** [comment]
These issues should probably be all in a single report as they're all related:
#299
#298 

It looks like the `$ia_id` var is not being set or passed to the template on creation. This handles taking the IA name https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/Cmd/New.pm#L158-L207

**Comment by jagtalon** [comment]
@MrChrisW you're right, they should all be in a single report. I'll make a new issue thanks!

**Comment by moollaza** [comment]
@jagtalon do you have the newest version of DuckPAN and the repos?

This seems to work correctly for me...

**Comment by jagtalon** [comment]
@moollaza just upgraded--looks fixed!
