### ISSUE TITLE
The ID of the Instant Answer isn't being written in some files after "duckpan new"

### ISSUE THREAD

**Issue by jagtalon** [duckduckgo/p5-app-duckpan#301]
- It says /js/spice//query instead of /js/spice/grunt/query:

![](https://cloud.githubusercontent.com/assets/81969/12348779/4cfb4eb6-bb38-11e5-8886-8ff339d5cb58.png)

- It put in Spice..content for me, but it should put in Spice.grunt.content:

![](https://cloud.githubusercontent.com/assets/81969/12347884/49c74b9e-bb30-11e5-95b0-495010c753c0.png)

- It's just env.ddg_spice_ instead of env.ddg_spice_grunt:

![](https://cloud.githubusercontent.com/assets/81969/12347831/a9d88968-bb2f-11e5-9011-f1cd5b82e003.png)

**Comment by jagtalon** [comment]
More related information from @MrChrisW: https://github.com/duckduckgo/p5-app-duckpan/issues/300#issuecomment-171902203

**Comment by MrChrisW** [comment]
>@jagtalon do you have the newest version of DuckPAN and the repos?

@moollaza You're right, I was able to reproduce this issue using version 0.192 of `App::DuckPAN` after upgrading to v0.198 this is fixed.

@jagtalon try updating and then attempt to reproduce the error :+1:

**Comment by jagtalon** [comment]
@MrChrisW @moollaza looks fixed! :+1:
