### ISSUE TITLE
Readme instructions location

### ISSUE THREAD

**Issue by talsraviv** [duckduckgo/p5-app-duckpan#324]
@moollaza so I realized there's a lot of overlap between this readme and the [other dev environments](http://docs.duckduckhack.com/resources/other-dev-environments.html) page - and now you've updated the readme.

I was thinking instead of having two repeated docs, would you prefer I just link to this readme, or that this readme link to the docs? 

Either way seems perfectly fine for me in this case, seems a matter of preference and workflow.

What do you think?

**Comment by moollaza** [comment]
> I was thinking instead of having two repeated docs, would you prefer I just link to this readme, or that this readme link to the docs?

Historically we didn't want to send all the devs away because most of them were installing DuckPAN. I think now that the majority are using Codio we no longer need to copy the DuckPAN readme into the docs.

Let's put a link to this README in the docs to keep things simple :+1:

**Comment by talsraviv** [comment]
Cool, will do
