### ISSUE TITLE
Allow `$lang` setting to be changed in DuckPAN server

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/p5-app-duckpan#325]
We should have `$lang` (and `$loc` if possible) be modifiable in DuckPAN server as if it were production. This would allow testing of language/location-based preferences without needing a full deploy.

**Comment by GuiltyDolphin** [comment]
Hmm.... It looks like we might be able to do this already with `DDG_TEST_LOCATION=loc duckpan server ...` - seems to be working locally.

@mintsoft Working for you too? If so I'll close this. (I tested with `DateMath` and `time now` (to see the time zone)).

**Comment by mintsoft** [comment]
@GuiltyDolphin sorry yeah that worked for me too
