### ISSUE TITLE
Cheat Sheets not displaying on DuckPAN Server

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/p5-app-duckpan#328]
Cheat Sheets are triggering, but not displaying on `duckpan server`. 

![screenshot from 2016-04-12 16 14 35](https://cloud.githubusercontent.com/assets/8598426/14465122/ad816e74-00c9-11e6-8540-a90022874339.png)

They are working fine with `duckpan query`, and the result shows in the log for `duckpan server`. All other Instant Answers appear to be unaffected (AFAIK).

/cc @moollaza @zachthompson

**Comment by moollaza** [comment]
Thanks, looking into it.

**Comment by moollaza** [comment]
Fixed in #329.

Users will need to update to newest DuckPAN in order for Goodies w/ templates and Cheat Sheets to work

/cc @duckduckgo/community-leaders -- please take note. I'll send out a broadcast on Slack as well
