### ISSUE TITLE
Replace use of File::ShareDir::ProjectDistDir

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/p5-app-duckpan#336]
> use of File::ShareDir::ProjectDistDir not advised
> Test::File::ShareDir is much simpler and less risky. See https://metacpan.org/pod/File::ShareDir::ProjectDistDir#DETERRENT

**Comment by moollaza** [comment]
It looks like `File::ShareDir` or `File::HomeDir` might be better? We're not using `ProjectDistDir` for testm but simply to load static files
