### ISSUE TITLE
Duckpan tester

### ISSUE THREAD

**Issue by yegg** [duckduckgo/p5-app-duckpan#34]
Since duckpan has dependencies on internal code, it can break without us realizing it (like it did the past day or so). We could use an automated testing script that we can run periodically to check if it is in a functional state or not. I imagine this would run independently of duckpan, spin up duckpan server and then run some tests against it. 

Part of the issue here, however, is that the error could be in JavaScript and that is hard to detect without something like Selenium. So maybe we do it that way, or maybe we treat those separately and for now we just run a script that tests more basic functioning, which could get most of the cases easily.

cc @nilnilnil @moollaza

**Comment by javathunderman** [comment]
@moollaza ping, is there any update on this?

**Comment by moollaza** [comment]
@javathunderman no, this isn't really a priority right now, we have different plans for the direction of duckpan and how IA's should be tested :)
