### ISSUE TITLE
Allow updating metadata through DuckPAN

### ISSUE THREAD

**Issue by GuiltyDolphin** [duckduckgo/p5-app-duckpan#348]
We already have support for _creating_ a duck.co account, so it would be really nice if we could allow the user to auth and update metadata for an Instant Answer through DuckPAN.

We could use this for things such as keeping files in-sync, and perhaps updating the development status of IAs.

It might make sense to have an 'in-development' version of the files, so the metadata for the live IA isn't incorrect.

**Comment by zachthompson** [comment]
The security implications with this aren't trivial.

We have a task internally to figure out how to have different versions of metadata.

**Comment by russellholt** [comment]
@GuiltyDolphin what do you mean by updating metadata with duckpan?

**Comment by GuiltyDolphin** [comment]
@russellholt For example, indicating that an IA is now in development, or updating which files belong to an IA (though the latter could probably be done on the platform).

I'm mostly thinking of during development (currently bumping IAs to development requires a PR); but it may be better to handle some of this stuff elsewhere (better detection of appropriate files on the platform).

**Comment by zachthompson** [comment]
Will pass on this.
