### ISSUE TITLE
Underscores in new cheat sheets

### ISSUE THREAD

**Issue by zachthompson** [duckduckgo/p5-app-duckpan#353]
When creating a skeleton cheat sheet with `--cheatsheet` it separates terms with an underscore in the name of the JSON file.  That's almost always wrong except in the rare cases when the underscore is part of the "thing" the cheat sheet is about. 

cc @GuiltyDolphin

**Comment by GuiltyDolphin** [comment]
@zachthompson Yup (I think I mentioned this briefly in https://github.com/duckduckgo/p5-app-duckpan/issues/347).

It's a combination of DuckPAN not providing enough information, and the template using the ID - I think we'd want to provide an underscored version of the ID for use in filenames (then you could use `<:$id_dash:>.json` instead. That, or we provide access to replacements in the templates so you could do `<:subst($ia_id, '_', '-'):>.json` (or similar).

Thoughts?

**Comment by zachthompson** [comment]
Yeah, it's just another exception somewhere for cheat sheets s/_/-/.
