### ISSUE TITLE
Cheat sheet template wizard should use hyphens

### ISSUE THREAD

**Issue by tagawa** [duckduckgo/p5-app-duckpan#355]
**Steps to reproduce:**
1. Launch the DuckPAN cheat sheet template wizard: `duckpan new --template cheatsheet`
2. Enter a name containing a space, e.g. "my test"
3. Press [Enter]

**What should happen:**
The resulting filename should contain a hyphen, e.g. `my-test.json`

**What actually happens:**
The resulting filename contains an underscore, e.g. `my_test.json`, meaning the cheat sheet isn't triggered.

**Comment by GuiltyDolphin** [comment]
@tagawa Yup - we've got an issue for it #353.
