### ISSUE TITLE
Installing DuckPAN fails at DDG-1006 (OSX perl v5.24.0)

### ISSUE THREAD

**Issue by xaviervalarino** [duckduckgo/p5-app-duckpan#364]
I've been having little success installing DuckPAN on my macbook with **perl v5.24.0**

I have attempted to install through the `install.pl` script, through `cpanm`, and `dzil build` from source.

The issue seems to lie with `DDG-1006`, with the `Experimental keys on scalar is now forbidden` appearing in the build logs. (Maybe I need to downgrade my version of perl?)

Curl Installation script
---
Installing through `curl http://duckpan.org/install.pl | perl` fails to install deps:
```
! Installing the dependencies failed: Module 'DDG::Test::Language' is not installed, Module 'DDG::Meta::Data' is not installed, Module 'DDG::Request' is not installed, Module 'DDG::Goodie' is not installed, Module 'DDG::Spice' is not installed, Module 'DDG::Test::Location' is not installed
! Bailing out the installation for App-DuckPAN-1008
```

cpanm DDG --mirror
---
Installing DDG through the Duckpan mirror:
```
cpanm DDG --mirror http://duckpan.org

! Finding DDG on cpanmetadb failed.
--> Working on DDG
Fetching http://duckpan.org/authors/id/Z/ZT/ZT/DDG-1006.tar.gz ... OK
Configuring DDG-1006 ... OK
Building and testing DDG-1006 ... FAIL
```
[see full cpanm build.log here](https://gist.github.com/xaviervalarino/6a8883b8f0fbfbc26690d7bc60347ff6#file-cpanm-fails-to-install-ddg-from-mirror)

Dzil build #362 
---

I have also attempted to `dzil build` @moollaza fork _**Skip several DDG::* dependencies**_ #362, hoping it would jump over this issue, but it also fails when building and testing DDG-1006.
```
[DZ] beginning to build App-DuckPAN
[Git::NextVersion] Bumping version from 1008 to 1009
[@Basic/ExtraTests] rewriting author test xt/author/pod-syntax.t
[DZ] writing App-DuckPAN in App-DuckPAN-1009
[Run::AfterBuild] executing: cpanm DDG --skip-installed --mirror http://www.cpan.org/ --mirror http://duckpan.org
[Run::AfterBuild] ! Finding DDG on cpanmetadb failed.
[Run::AfterBuild] ! Finding DDG () on mirror http://www.cpan.org failed.
[Run::AfterBuild] ! Download http://www.cpan.org/authors/id/Z/ZT/ZT/DDG-1006.tar.gz failed. Retrying ...
[Run::AfterBuild] ! Download http://www.cpan.org/authors/id/Z/ZT/ZT/DDG-1006.tar.gz failed. Retrying ...
[Run::AfterBuild] ! Download http://www.cpan.org/authors/id/Z/ZT/ZT/DDG-1006.tar.gz failed. Retrying ...
[Run::AfterBuild] ! Failed to download http://www.cpan.org/authors/id/Z/ZT/ZT/DDG-1006.tar.gz
[Run::AfterBuild] --> Working on DDG
[Run::AfterBuild] Fetching http://www.cpan.org/authors/id/Z/ZT/ZT/DDG-1006.tar.gz ... FAIL
[Run::AfterBuild] Fetching http://duckpan.org/authors/id/Z/ZT/ZT/DDG-1006.tar.gz ... OK
[Run::AfterBuild] Configuring DDG-1006 ... OK
[Run::AfterBuild] Building and testing DDG-1006 ... ! Installing DDG failed. See /Users/Xavier/.cpanm/work/1469047477.2898/build.log for details. Retry with --force to force install it.
[Run::AfterBuild] FAIL
[Run::AfterBuild] command exited with status 1 (256)
[Run::AfterBuild] command exited with status 1 (256) at /Users/Xavier/perl5/lib/perl5/darwin-thread-multi-2level/Moose/Meta/Method/Delegation.pm line 110.
````
[see full cpanm build.log here](https://gist.github.com/xaviervalarino/6a8883b8f0fbfbc26690d7bc60347ff6#file-dzil-fails-to-build-app-duckpan-1009-skip-ddg-deps-fork)

**Comment by xaviervalarino** [comment]
After downgrading to perl v5.18.2, I successfully install DuckPAN by building it from @moollaza's fork, although I had to `dzil build` [Dist::Zilla::Plugin::UploadToDuckPAN](https://github.com/duckduckgo/p5-dist-zilla-plugin-uploadtoduckpan) from source.

**Comment by moollaza** [comment]
> although I had to dzil build Dist::Zilla::Plugin::UploadToDuckPAN from source.

@xaviervalarino why did you have to build it from source? What failed?

**Comment by xaviervalarino** [comment]
@moollaza looking through the build.log, it looks as though it wasn't able to find it on the mirror.
 I attempted to reproduce this error by uninstalling `App::DuckPAN` and `Dist::Zilla::Plugin::UploadToDuckPAN ` and then reinstalling DuckPAN, but it installed with no problems.
Maybe it was just a connectivity issue?

Should I close this ticket, or do you still want to keep it open since there is still the issue with the stricter scalars in v5.24?

**Comment by moollaza** [comment]
@xaviervalarino I'm going to close for now as we don't actually support Perl 5.24. It helps to know that we may see breakage in the future though 👍
