### ISSUE TITLE
Fathead support: Non-matching queries return last match

### ISSUE THREAD

**Issue by jbarrett** [duckduckgo/p5-app-duckpan#365]
In other words, "Sorry, no results were returned from Instant Answer" only triggers until a match is found. After that you'll get the last matching entry for non-matching queries.

Steps to reproduce:

- Query a matching entry in a fathead.
- Query a non-matching entry in a fathead.

Symptom:

- The last matching entry is presented

Expected output:

- "Sorry, no results were returned from Instant Answer"

**Comment by GuiltyDolphin** [comment]
@jbarrett This was really bugging me so I've gone ahead and pushed a fix, does it work fine for you?

**Comment by jbarrett** [comment]
:+1: LGTM, thanks @GuiltyDolphin!

Going to close this since I'm pretty sure #358 will be merged soonly.
