### ISSUE TITLE
"duckpan new --template cheatsheet" should use dashes for filename, not underscores

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/p5-app-duckpan#369]
When creating a cheat sheet with `duckpan new --template cheatsheet` the generated filename is created using `_` instead of `-`.

e.g. "ufc_weight_classes.json" instead of "ufc-weight-classes.json"

However, `duckpan new --cheatsheet` works correctly.

I've updated the documentation to use the latter as it's more straightforward. We should correct the filename craetion or we could also remove the `--template cheatsheet` option altogether?

**Comment by GuiltyDolphin** [comment]
@moollaza I thought I fixed this? Seems to be working for me:

![screenshot-2016-08-05-17 37 59_484_100](https://cloud.githubusercontent.com/assets/8598426/17443610/6b133e2c-5b33-11e6-91c8-1795938d35ef.png)

**Comment by moollaza** [comment]
@GuiltyDolphin really odd, It definitely didn't work a couple days ago when I was helping @edgesince84 . It must have been an old DuckPAN...

Working now that I tested again locally 👍 

> I'm thinking we should perhaps restrict the input to IDs (/use the input to generate an ID) so we can use metadata to generate the file?

I'm not sure we want that because you'd be forced to create an IA Page just to generate your code.  There's definitely room for improvement regarding the IA Page to code creation process though.

**Comment by GuiltyDolphin** [comment]
> I'm not sure we want that because you'd be forced to create an IA Page just to generate your code. There's definitely room for improvement regarding the IA Page to code creation process though. 

@moollaza True, though it may make sense as we move to a more meta-data--oriented approach to cheat sheets. We can think about it then if required.
