### ISSUE TITLE
Test a new goodie

### ISSUE THREAD

**Issue by kirkins** [duckduckgo/p5-app-duckpan#390]
I submitted a new Goodie for text to voice and I found a small issue in Duckpan during the development process.

If you want to query the new goodie there is no problem, though you do get a warning like this:

    [NOTICE] No metadata was found for these Instant Answers:

But if I try to test the new goodie:

    [FATAL]  Could not find an Instant Answer with name 'TextToSpeech'

As a workaround I used a full `duckpan test`, which ended up consuming a lot of time while working on tests.

**Comment by mintsoft** [comment]
As a smaller workaround you can use `prove -Ilib t/TextToSpeech.t` from the root of the repository, that should work. It looks like this got missed in https://github.com/duckduckgo/p5-app-duckpan/pull/383
