### ISSUE TITLE
Feature Request: DuckPAN Package/Code Reloading

### ISSUE THREAD

**Issue by zekiel** [duckduckgo/p5-app-duckpan#52]
Currently DuckPAN does not listen for changes in the Spice or Goodie packages it has loaded. Adding this ability would greatly benefit developers as they currently are required to restart the DuckPAN Server after making any modifications to `.pm` files in order for them to take effect.

**Comment by moollaza** [comment]
Fixed! Thanks to #196

**Comment by MrChrisW** [comment]
@moollaza Can we modify this at all not to reload on js or css files? `(?i)(js|css)$` https://github.com/duckduckgo/p5-app-duckpan/blob/master/lib/App/DuckPAN/Restart.pm#L95

No need to reload the server for js or css changes? Unless a flush of cache is required?

**Comment by moollaza** [comment]
@MrChrisW that sounds like a good idea, the CSS/JS gets pulled on refresh, so it might be overkill to restart the process for those.

@zachthompson any thoughts?

**Comment by zachthompson** [comment]
@moollaza @MrChrisW That would probably be fine.  Most files in share don't require a reload, except for the *.txt files.

**Comment by moollaza** [comment]
@MrChrisW care to submit a PR? or make an issue?

**Comment by zachthompson** [comment]
@moollaza @MrChrisW See if https://github.com/duckduckgo/p5-app-duckpan/pull/218 does what you expect.  There are more than .txt files in /share/ that might require a reload, e.g. .yml.  So it just skips js, css, and handlebars files.

**Comment by moollaza** [comment]
Fixed in #128
